export const HTTP_BAD_REQUEST = 400
export const HTTP_REQUEST_TIMEOUT = 408
export const HTTP_TOO_MANY_REQUESTS = 429
export const HTTP_BAD_GATEWAY = 502
export const HTTP_SERVICE_UNAVAILABLE = 503

export const TRANSIENT_STATUS_CODES = new Set([HTTP_REQUEST_TIMEOUT, HTTP_TOO_MANY_REQUESTS, HTTP_BAD_GATEWAY, HTTP_SERVICE_UNAVAILABLE])
